services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: strongpswd
      WORDPRESS_DB_NAME: cmsdbfcta
    volumes:
      - ./wp_data:/var/www/html
    networks:
      - wpnet

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cmsdbfcta
      MYSQL_USER: wp
      MYSQL_PASSWORD: strongpswd
      MYSQL_ROOT_PASSWORD: superstrongpswd
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - wpnet

volumes:
  wp_data:
  db_data:

networks:
  wpnet:
    name: WPNet
    driver: bridge