networks:
  mynetwork:
    external: true

services:

  wpcms:
    container_name: wpcms
    image: wordpress:6.7.2-php8.1-apache
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - ./wp:/var/www/html
    networks:
      - mynetwork
    security_opt:
      - no-new-privileges:true
    user: "33:33"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - ./wp_db:/var/lib/mysql
    networks:
      - mynetwork
    security_opt:
      - no-new-privileges:true
    user: "999:999"

volumes:
  wp:
  wp_db: